### ISSUE TITLE
Prince of Persia IGT Displayer -  Stuck at 0:00.000 in Level Skip categories

### ISSUE THREAD

**Issue by 7eraser7** [WinterThunderSpeedrun/Autosplitters#4]
After the last commit, the igt displayer can be stuck at zero when playing a "Level Skip" category.
Easily reproductible, just skip the level 1 fast enough.

Here are a couple of examples of it not working and then working:
https://clips.twitch.tv/ShakingCleanHerbsKeepo-BL-GdkVv-4hFP8Yy

Severity: Medium since there is a workaround but you have to know it.

**Comment by WinterThunderSpeedrun** [comment]
Fixed by GMP: corrected Level Skip detection condition.
